param([string]$AddonName = "erea-rp-custom-videos")

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$blpFolder = Join-Path $scriptDir "blp-videos"

if (-not (Test-Path $blpFolder)) { Write-Error "blp-videos folder not found"; exit 1 }

$blpFiles = Get-ChildItem -Path $blpFolder -Filter "*.blp" | Sort-Object Name
foreach ($blp in $blpFiles) {
    $sanitizedName = $blp.BaseName -replace '[^a-zA-Z0-9_]', '_'
    if ($sanitizedName -ne $blp.BaseName) {
        Rename-Item -Path $blp.FullName -NewName "$sanitizedName.blp"
        Write-Host "Renamed $($blp.Name) -> $sanitizedName.blp"
    }
}

$blpFiles = Get-ChildItem -Path $blpFolder -Filter "*.blp" | Sort-Object Name
$lines = @(
    "-- Custom animation registry - auto-generated by generate-registry.ps1, do not edit manually",
    "-- To add animations: place .blp sprite-sheet files in this folder and run generate-registry.ps1",
    "-- Keys must be globally unique. Use a distinctive prefix to avoid conflicts with other addons.",
    "EreaRpCustomVideoRegistry = {"
)
foreach ($blp in $blpFiles) {
    $key = $blp.BaseName.ToLower()
    $texturePath = "Interface\\AddOns\\$AddonName\\blp-videos\\" + $blp.BaseName
    $lines += "    $key = {"
    $lines += "        texture = `"$texturePath`","
    $lines += "        cols = 4, rows = 4, totalFrames = 16, fps = 8"
    $lines += "    },"
}
$lines += "}"

$outputPath = Join-Path $blpFolder "animation-registry.lua"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, ($lines -join "`n"), $utf8NoBom)
Write-Host "Generated animation-registry.lua with $($blpFiles.Count) entries"
