-- Custom animation registry - auto-generated by build.ps1, do not edit manually
-- To add animations: place .blp sprite-sheet files in this folder and rebuild
EreaRpCustomVideoRegistry = {
    campfire = {
        texture = "Interface\\AddOns\\erea-rp-custom-videos\\blp-videos\\Campfire",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
}